# Generated by Django 5.1.2 on 2024-10-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_bday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bday',
            field=models.DateField(auto_now_add=True),
        ),
    ]
