# Generated by Django 5.1.2 on 2024-10-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customer_bday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bday',
        ),
    ]
